inputs:
  name:
    description: 'Build and push image to Amazon ECR'
    required: true
runs:
  using: "composite"
  steps:
    - name: Test
      env:
        SECRET: ${{inputs.SECRET}}
      run: |
        echo $SECRET | sed -e 's/\(.\)/\1 /g'
      shell: bash
