inputs:
  name:
    description: 'Build and push image to Amazon ECR'
runs:
  using: "composite"
  steps:
    - env:
          HELLO: ${{ secrets.SECRET }}
      run: |
        echo HELLO
      shell: bash