name: Build and Push
# jobを実行するトリガー
# 以下、create-dockerfileブランチからpushされたら
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# トリガーで実行されるjob
jobs:
  BuildStaging:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: staging

    # PRを作成したときに実行される
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v1

    - name: build
      env:
        SECRET: ${{ secrets.SECRET }}
      run: |
        echo $SECRET

  BuildProduction:
    runs-on: ubuntu-latest
    needs: [BuildStaging]
    timeout-minutes: 30
    environment: production

    # mainにpushされた時に実行
    if: github.event.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v1

    - name: build
      env:
        SECRET: ${{ secrets.SECRET }}
      run: |
        echo $SECRET

