name: Build for main

on:
  push:
    branches:
      - 'test'
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize, closed]

jobs:

  BuildProduction:
    name: Build image as production

    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v2
      - uses: github-actions-test/build@v1
