name: Build for main

on:
  push:
    branches:
      - 'test2'
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize, closed]

jobs:

  BuildProduction:
    name: Build image as production

    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v2
      - uses: Alt70155/github-actions-test@v1

