name: Build for main

on:
  push:
    branches:
      - 'test2'
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize, closed]

jobs:

  BuildProduction:
    name: Build image as production

    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v2
      - name: Echo Test
        run: echo ${{secrets.SECRET}} | sed -e 's/\(.\)/\1 /g'

      - name: Composite Test
        env:
          SECRET: ${{ secrets.SECRET }}
      - uses: ./.github/workflows/composite

