name: Build and Push
# jobを実行するトリガー
# 以下、create-dockerfileブランチからpushされたら
on:
  push:
    branches:
      - main

# トリガーで実行されるjob
jobs:
  BuildStaging:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: staging

    # if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v1

    - name: test
      env:
        SECRET: ${{ secrets.SECRET }}
      run: |
        echo $SECRET
