name: Build for main

on:
  push:
    branches:
      - 'test2'

jobs:

  BuildStaging:
    name: Build image as Staging

    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v2
      # - name: Echo Test
      #   env:
      #       SECRET: ${{ secrets.SECRET }}
      #   run: echo ${{secrets.SECRET}} | sed -e 's/\(.\)/\1 /g'

      - name: Composite Test
        uses: ./.github/workflows/composite
        with:
          secret: ${{ secrets.SECRET }}
