name: Build and Push
# jobを実行するトリガー
# 以下、create-dockerfileブランチからpushされたら
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# トリガーで実行されるjob
jobs:
  BuildStaging:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: production

    # トリガーが実行されたら必ず実行される
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v1

    - name: Setup tmate session
      env:
          SECRET: ${{ secrets.SECRET }}
          AWS_ECR_REPO_NAME: ${{ secrets.AWS_ECR_REPO_NAME }}
      uses: mxschmitt/action-tmate@v3

    # - name: build
    #   env:
    #     SECRET: ${{ secrets.SECRET }}
    #   run: |
    #     echo $SECRET

  BuildProduction:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: production

    # mainにpushされた時に実行(PRがmergeされても実行される)
    if: github.event.ref == 'refs/heads/main'
    needs: [BuildStaging]
    steps:
    - uses: actions/checkout@v1

    - name: build
      env:
        SECRET: ${{ secrets.SECRET }}
      run: |
        echo $SECRET

