name: Build for main

on:
  push:
    branches:
      - 'test2'

jobs:

  BuildStaging:
    name: Build image as Staging

    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v2
      - name: Echo Test
        env:
            SECRET: ${{ secrets.SECRET }}
            ENV: ${{ environment }}
        run: |
          echo ${{secrets.SECRET}} | sed -e 's/\(.\)/\1 /g'
          echo $SECRET | sed -e 's/\(.\)/\1 /g'
          echo ${{ENV}} | sed -e 's/\(.\)/\1 /g'

      # - name: Composite Test
      #   uses: ./.github/workflows/composite
      #   with:
      #     secret: ${{ environment }}
