name: CI/CD for release

# 予想：mainへのPR/Push、releaseへのPR/Push全てのアクションでトリガーを起動する必要があり、トリガーの中のifで、実行するジョブを分岐させる
on:
  pull_request:
    branches:
      - 'release'
    types: [opened, synchronize, closed]

# トリガーで実行されるjob
jobs:
  # releaseブランチにmergeされたら実行したい
  BuildProduction:
    name: Build image as production

    # releaseにpushされた時に実行する(PRがmergeされても実行される)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v1

    - name: build
      env:
        SECRET: ${{ secrets.SECRET }}
      run: |
        echo $SECRET

