name: Build for release

on:
  pull_request:
    branches:
      - 'release'
    types: [opened, synchronize, closed]

# トリガーで実行されるjob
jobs:
  # PRがreleaseブランチにmergeされたら実行する
  BuildProduction:
    name: Build image as production

    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: prd

    steps:
      - uses: actions/checkout@v2
        with:
          # fetch all history to find all related pull requests.
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
    
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest --build-arg TARGET_ENV='prd'  .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
